[package]
name = "ytd-daemon"
version = "1.0.10"
edition = "2021"
license = "MIT"
description = "YTD - YouTube & YT Music Downloader Desktop Daemon"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.8.9"
tower-http = { version = "0.7.1", features = ["cors"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5"
dirs = "7.0.0"
rfd = "0.17.2"
tray-icon = "0.25"
tauri-winrt-notification = "0.8.1"
open = "5.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
windows-sys = { version = "0.61.2", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_System_Registry",
    "Win32_System_Threading",
] }
github-auto-updater = { git = "https://github.com/FunToHard/github-auto-updater-rs.git", branch = "main" }
sha2 = "0.11"

[build-dependencies]
winres = "0.1"
